version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - webnet
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - webnet
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
networks:
  webnet:
    driver: bridge
